version: "3"
services:
  consent-management:
    image: consent-management:latest
    ports:
      - "8080:8080"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
  kalix-proxy:
    image: gcr.io/kalix-public/kalix-proxy:1.1.6
    command: -Dconfig.resource=dev-mode.conf -Dlogback.configurationFile=logback-dev-mode.xml #-Dkalix.proxy.eventing.support=google-pubsub-emulator
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8080}
      # Comment to enable ACL check in dev-mode (see https://docs.kalix.io/services/using-acls.html#_local_development_with_acls)
      ACL_ENABLED: 'false'


