version: "3"
services:
  consent-management:
    image: consent-management:latest
    depends_on:
      - kalix-proxy
    ports:
      - "8080:8080"
    environment:
      HOST: consent-management
  kalix-proxy:
    image: gcr.io/kalix-public/kalix-proxy:1.1.6
    command: -Dconfig.resource=dev-mode.conf -Dlogback.configurationFile=logback-dev-mode.xml
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      USER_FUNCTION_HOST: consent-management
      USER_FUNCTION_PORT: 8080
      ACL_ENABLED: 'false'


